# This is a basic workflow to help you get started with Actions

name: Caprover Delete App

on:
  workflow_call: 
    secrets:
      caproverPassword:
        required: true
        description: Caprover password
    inputs:
      caproverAppName:
        required: true
        type: string
      caproverDomain:
        required: true
        type: string
      envFile:
        required: false
        type: string
      caproverImageName:
        required: false
        type: string
        default: "ghcr.io/${{ github.repository }}:${{ github.sha }}"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: cardinalby/export-env-action@4f48c4676cf6ed6f46e30899ee987ce695da7c80 # 2.2.3
        if: ${{ inputs.envFile }}
        with:
          envFile: ${{ inputs.envFile }}

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Delete Caprover App 🗑️
        run: bunx caprover api --path=/user/apps/appDefinitions/delete --method=POST --data='{"appName":"${{ inputs.caproverAppName }}"}' || true
        env:
          CAPROVER_URL: https://captain.${{ inputs.caproverDomain }}
          CAPROVER_PASSWORD: ${{ secrets.caproverPassword }}
          CAPROVER_IMAGE_NAME: ${{ inputs.caproverImageName }}
          CAPROVER_APP: ${{ inputs.caproverAppName }}
