# This is a basic workflow to help you get started with Actions

name: EAS Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_call:
    inputs:
      no_wait:
        description: If the build should wait for the build to finish
        required: false
        default: true
        type: boolean
      working_directory:
        type: string
        default: .
        description: The working directory to run the workflow in.
        required: false
      env_inline:
        type: string
        description: Pass any environment variables to the publish command here, for passing to app.config.js. Could be "APP_ENV=staging MY_OTHER_VAR=hey" for example
        required: false
      platform:
        type: string
        description: ios or android
        required: true
      expo_app_slug:
        type: string
        description: The expo app slug
        required: false
      expo_organisation_or_user_slug:
        type: string
        description: The organisation/user slug you're publishing to
        required: false
        default: kingstinct
      build_profile:
        type: string
        description: The build profile to use, staging or production for example
        required: true
      always_run:
        type: boolean
        description: Run even if there's a build with the same hash (finished or in progress)
        required: false
        default: false
      package_manager:
        required: false
        type: string
        default: yarn
        description: The package manager to use
      env_file:
        required: false
        type: string
        description: .env file to automatically add to Github context
      autosubmit:
        required: false
        type: boolean
        default: false
        description: Autosubmit to AppStore/PlayStore
      checkout_ref:
        required: false
        type: string
        description: The ref to checkout
      pnpm_version:
        required: false
        type: string
        description: If using pnpm - which version to use (defaults to the packageManager field in package.json)
      nodeModulePaths:
        required: false
        type: string
        default: node_modules
        description: nodeModulePaths to use when checking current hash
      google_service_account_key_path:
        required: false
        type: string
        default: ./google-service-account-key.json
        description: The path to the google-service-account-key.json file
      bun_version:
        required: false
        type: string
        description: Set bun version
      env_template_file:
        type: string
        description: The Path to the .env template file
        required: false
    secrets:
      EXPO_TOKEN:
        description: The Expo token to use for publishing
        required: true
      EXPO_APPLE_APP_SPECIFIC_PASSWORD:
        description: The Apple App Specific Password to use for publishing to AppStore (required for autosubmit)
        required: false
      GOOGLE_SERVICE_ACCOUNT_KEY_JSON:
        description: The Google Services JSON to use for publishing to PlayStore (required for autosubmit)
        required: false
      SLACK_WEBHOOK:
        description: The Slack Webhook to use for notifications
        required: false
      DISCORD_WEBHOOK:
        description: The Discord Webhook to use for notifications
        required: false
      OP_SERVICE_ACCOUNT_TOKEN:
        description: The 1Password service account token
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  eas-build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      buildId: ${{ steps.buildId.outputs.buildId }}
      buildUrl: ${{ steps.buildUrl.outputs.buildUrl }}
    env:
      EXPO_DEBUG: 1
      DEBUG: 1
      EAS_BUILD_AUTOCOMMIT: ${{ inputs.autosubmit }}
      GOOGLE_SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_JSON }}
      EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        if: ${{ !inputs.checkout_ref }}

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@a5215d3a7f75c1629216c465ea9ab3ab399c4b71 # v4.0.0
        if: ${{ env.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load secret
        uses: 1password/load-secrets-action/configure@3a12b0ab99d9cd590a3e9b5a90ea017210ed9556 # v4.0.1
        if: ${{ env.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Build .env.production
        run: op inject -i ${{ inputs.env_template_file }}.tpl -o ${{ inputs.env_template_file }}
        if: ${{ inputs.env_template_file && env.OP_SERVICE_ACCOUNT_TOKEN }}
        working-directory: ${{ inputs.working_directory }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        if: ${{ inputs.checkout_ref }}
        with:
          ref: ${{ inputs.checkout_ref }}

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        if: ${{ inputs.package_manager == 'pnpm' }}
        with:
          version: ${{ inputs.pnpm_version }}

      - uses: cardinalby/export-env-action@4f48c4676cf6ed6f46e30899ee987ce695da7c80 # 2.2.3
        if: ${{ inputs.env_file }}
        with:
          envFile: ${{ inputs.env_file }}

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        if: ${{ inputs.package_manager == 'bun' }}
        with:
          bun-version: ${{ inputs.bun_version || env.BUN_VERSION || 'latest' }}

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        if: ${{ inputs.package_manager != 'bun' }}
        with:
          node-version-file: .nvmrc
          cache: ${{ inputs.package_manager }}

      - name: Install dependencies (bun)
        run: ${{ inputs.package_manager }} install --frozen-lockfile
        if: ${{ inputs.package_manager == 'bun' }}
        working-directory: ${{ inputs.working_directory }}

      - name: Install dependencies (npm)
        run: npm ci
        if: ${{ inputs.package_manager == 'npm' }}
        working-directory: ${{ inputs.working_directory }}

      - name: Install dependencies (others)
        run: ${{ inputs.package_manager }} install --frozen-lockfile
        if: ${{ inputs.package_manager != 'npm' && inputs.package_manager != 'bun' }}
        working-directory: ${{ inputs.working_directory }}

      - name: Expo GitHub Action
        uses: expo/expo-github-action@eab7a230208c952974db8c3245cfd78402c7b385 # v9.0.0
        id: expo-init
        with:
          # Your Expo username, for authentication.
          token: ${{ secrets.EXPO_TOKEN }}
          # If Expo should be stored in the GitHub Actions cache (can be true or false)
          expo-version: latest
          eas-version: latest
          packager: ${{ inputs.package_manager }}
          expo-cache: true # optional

      - name: Get Hash
        if: ${{ !inputs.always_run }}
        run: echo "HASH=`jq -r '.expo.${{ inputs.platform }}.runtimeVersion' app.json`" >> $GITHUB_ENV
        working-directory: ${{ inputs.working_directory }}

      - name: Matching Native Builds
        if: ${{ !inputs.always_run }}
        run: echo "MATCHING_FINISHED_BUILDS=`${{ inputs.env_inline }} npx eas-cli@latest build:list --buildProfile=${{ inputs.build_profile }} --platform=${{ inputs.platform }} --status=finished | grep -c $HASH`" >> $GITHUB_ENV
        working-directory: ${{ inputs.working_directory }}

      - name: Matching In-Progress Builds
        if: ${{ !inputs.always_run }}
        run: echo "MATCHING_IN_PROGRESS_BUILDS=`${{ inputs.env_inline }} npx eas-cli@latest build:list --buildProfile=${{ inputs.build_profile }} --platform=${{ inputs.platform }} --status=in-progress | grep -c $HASH`" >> $GITHUB_ENV
        working-directory: ${{ inputs.working_directory }}

      - name: Matching In-Queue Builds
        if: ${{ !inputs.always_run }}
        run: echo "MATCHING_IN_QUEUE_BUILDS=`${{ inputs.env_inline }} npx eas-cli@latest build:list --buildProfile=${{ inputs.build_profile }} --platform=${{ inputs.platform }} --status=in-queue | grep -c $HASH`" >> $GITHUB_ENV
        working-directory: ${{ inputs.working_directory }}

      - name: Matching New Builds
        if: ${{ !inputs.always_run }}
        run: echo "MATCHING_NEW_BUILDS=`${{ inputs.env_inline }} npx eas-cli@latest build:list --buildProfile=${{ inputs.build_profile }} --platform=${{ inputs.platform }} --status=new | grep -c $HASH`" >> $GITHUB_ENV
        working-directory: ${{ inputs.working_directory }}

      - name: create google-services.json
        id: init-google-services-json
        if: ${{ inputs.platform == 'android' && inputs.autosubmit && env.GOOGLE_SERVICE_ACCOUNT_KEY_JSON  }}
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_JSON }}" > ${{ inputs.google_service_account_key_path }}

      - name: EAS Build
        if: ${{ inputs.no_wait && inputs.autosubmit && (inputs.always_run || (env.MATCHING_IN_PROGRESS_BUILDS == 0 && env.MATCHING_FINISHED_BUILDS == 0 && env.MATCHING_IN_QUEUE_BUILDS == 0 && env.MATCHING_NEW_BUILDS == 0)) }}
        run: |
          BUILD_ID=`set -e; npx eas-cli@latest build --no-wait --non-interactive --profile=${{ inputs.build_profile }} --auto-submit --platform ${{ inputs.platform }} --json | jq ".[].id"`
          BUILD_ID=`echo $BUILD_JSON | jq ".[].id"`
          echo "BUILD_ID=${BUILD_ID}" >> $GITHUB_ENV
          BUILD_STATUS=`echo $BUILD_JSON | jq ".[].id"`
          echo "BUILD_STATUS=${BUILD_STATUS}" >> $GITHUB_ENV
        working-directory: ${{ inputs.working_directory }}

      - name: EAS Build
        if: ${{ inputs.no_wait && !inputs.autosubmit && (inputs.always_run || (env.MATCHING_IN_PROGRESS_BUILDS == 0 && env.MATCHING_FINISHED_BUILDS == 0 && env.MATCHING_IN_QUEUE_BUILDS == 0 && env.MATCHING_NEW_BUILDS == 0)) }}
        run: |
          BUILD_JSON=`set -e; npx eas-cli@latest build --no-wait --non-interactive --profile=${{ inputs.build_profile }} --platform ${{ inputs.platform }} --json`
          BUILD_ID=`echo $BUILD_JSON | jq ".[].id"`
          echo "BUILD_ID=${BUILD_ID}" >> $GITHUB_ENV
          BUILD_STATUS=`echo $BUILD_JSON | jq ".[].id"`
          echo "BUILD_STATUS=${BUILD_STATUS}" >> $GITHUB_ENV
        working-directory: ${{ inputs.working_directory }}

      - name: EAS Build
        if: ${{ !inputs.no_wait && inputs.autosubmit && (inputs.always_run || (env.MATCHING_IN_PROGRESS_BUILDS == 0 && env.MATCHING_FINISHED_BUILDS == 0 && env.MATCHING_IN_QUEUE_BUILDS == 0 && env.MATCHING_NEW_BUILDS == 0)) }}
        run: |
          BUILD_JSON=`set -e; npx eas-cli@latest build --non-interactive --profile=${{ inputs.build_profile }} --auto-submit --platform ${{ inputs.platform }} --json`
          BUILD_ID=`echo $BUILD_JSON | jq ".[].id"`
          echo "BUILD_ID=${BUILD_ID}" >> $GITHUB_ENV
          BUILD_STATUS=`echo $BUILD_JSON | jq ".[].id"`
          echo "BUILD_STATUS=${BUILD_STATUS}" >> $GITHUB_ENV
        working-directory: ${{ inputs.working_directory }}

      - name: EAS Build
        if: ${{ !inputs.no_wait && !inputs.autosubmit && (inputs.always_run || (env.MATCHING_IN_PROGRESS_BUILDS == 0 && env.MATCHING_FINISHED_BUILDS == 0 && env.MATCHING_IN_QUEUE_BUILDS == 0 && env.MATCHING_NEW_BUILDS == 0)) }}
        run: |
          BUILD_JSON=`set -e; npx eas-cli@latest build --non-interactive --profile=${{ inputs.build_profile }} --platform ${{ inputs.platform }} --json`
          BUILD_ID=`echo $BUILD_JSON | jq ".[].id"`
          echo "BUILD_ID=${BUILD_ID}" >> $GITHUB_ENV
          BUILD_STATUS=`echo $BUILD_JSON | jq ".[].id"`
          echo "BUILD_STATUS=${BUILD_STATUS}" >> $GITHUB_ENV
        working-directory: ${{ inputs.working_directory }}

      - name: Fail if no build was created when expected
        run: exit 1
        if: ${{ ((!env.BUILD_ID && !inputs.no_wait) || env.BUILD_STATUS == 'ERRORED') && ((env.MATCHING_IN_PROGRESS_BUILDS == 0 && env.MATCHING_FINISHED_BUILDS == 0 && env.MATCHING_IN_QUEUE_BUILDS == 0 && env.MATCHING_NEW_BUILDS == 0) || inputs.always_run) }}

      - run: echo "buildUrl=https://expo.dev/accounts/${{ inputs.expo_organisation_or_user_slug }}/projects/${{ inputs.expo_app_slug }}/builds/${{ env.BUILD_ID }}" > "$GITHUB_OUTPUT"
        id: buildUrl
        if: ${{ env.BUILD_ID && inputs.expo_app_slug }}

      - run: echo "buildId=${{ env.BUILD_ID }}" > "$GITHUB_OUTPUT"
        id: buildId
        if: ${{ env.BUILD_ID }}

      - uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1.16.0
        if: ${{ failure() && env.DISCORD_WEBHOOK }}
        with:
          webhook: ${{ env.DISCORD_WEBHOOK }}
          url: ${{ env.BUILD_URL }}

      - uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        if: ${{ failure() && env.SLACK_WEBHOOK }}
