name: Playwright Tests
on:
  workflow_call:
    inputs:
      repository:
        default: Kingstinct/schedulist-app
        description: The repository where the tests are
        required: false
        type: string
      PLAYWRIGHT_TEST_URL:
        default: https://master.schedulist-app.pages.dev/
        type: string
        required: false
      package_manager:
        required: false
        type: string
        default: yarn
        description: The package manager to use
      pnpm_version:
        required: false
        type: string
        description: If using pnpm - which version to use (defaults to the packageManager field in package.json)
      shard_count:
        required: false
        type: number
        default: 1
        description: Number of shards to split the tests into
      shard_index:
        required: false
        type: number
        description: Which shard is this, starting from 1
      env_file:
        required: false
        type: string
        description: The .env file to use
      working_directory:
        required: false
        type: string
        default: .
        description: The working directory to run the tests in
    secrets:
      GITHUB_PAT:
        required: false
        description: Personal access token to access the repo with tests
      SLACK_WEBHOOK:
        description: The Slack Webhook to use for notifications
        required: false
      DISCORD_WEBHOOK:
        description: The Discord Webhook to use for notifications
        required: false
  workflow_dispatch:
    inputs:
      PLAYWRIGHT_TEST_URL:
        description: URL to run playwright tests towards
        default: https://master.schedulist-app.pages.dev/
        type: string
        required: false
      repository:
        default: Kingstinct/schedulist-app
        description: The repository where the tests are
        required: false
        type: string
      package_manager:
        required: false
        type: string
        default: yarn
        description: The package manager to use
      pnpm_version:
        required: false
        type: string
        description: If using pnpm - which version to use (defaults to the packageManager field in package.json)
      working_directory:
        required: false
        type: string
        default: .
        description: The working directory to run the tests in

jobs:
  e2e:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      npx: ${{ inputs.package_manager == 'bun' && 'bunx' || 'npx' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ${{ inputs.repository }}
          token: ${{ secrets.GITHUB_PAT }}

      - uses: cardinalby/export-env-action@4f48c4676cf6ed6f46e30899ee987ce695da7c80 # 2.2.3
        if: ${{ inputs.env_file }}
        with:
          envFile: ${{ inputs.env_file }}

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        if: ${{ inputs.package_manager == 'bun' }}
        with:
          bun-version: ${{ inputs.bun-version || env.BUN_VERSION }}

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        if: ${{ inputs.package_manager == 'pnpm' }}
        with:
          version: ${{ inputs.pnpm_version }}

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        if: ${{ inputs.package_manager == 'node' }}
        with:
          node-version-file: .nvmrc
          cache: ${{ inputs.package_manager }}

      - name: Install dependencies (npm)
        run: npm ci
        if: ${{ inputs.package_manager == 'npm' }}
        working-directory: ${{ inputs.working_directory }}

      - name: Install dependencies (others)
        run: ${{ inputs.package_manager }} install --frozen-lockfile
        if: ${{ inputs.package_manager != 'npm' }}
        working-directory: ${{ inputs.working_directory }}

      - name: Install Playwright Browsers
        run: ${{ env.npx }} playwright install --with-deps

      - name: Run Playwright tests
        if: ${{ inputs.shard_count == 1 }}
        run: PLAYWRIGHT_TEST_URL=${{ inputs.PLAYWRIGHT_TEST_URL }} ${{ env.npx }} playwright test

      - name: Run Playwright tests sharded
        if: ${{ inputs.shard_count > 1 }}
        run: PLAYWRIGHT_TEST_URL=${{ inputs.PLAYWRIGHT_TEST_URL }} ${{ env.npx }} playwright test --shard=${{ inputs.shard_index }}/${{ inputs.shard_count }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: "${{ inputs.shard_count > 1 && format('playwright-report-{0}', inputs.shard_index || 1) || 'playwright-report' }}"
          path: playwright-report/
          retention-days: 30

      - uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1.16.0
        if: ${{ failure() && env.DISCORD_WEBHOOK }}
        with:
          webhook: ${{ env.DISCORD_WEBHOOK }}

      - uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        if: ${{ failure() && env.SLACK_WEBHOOK }}